name: Generate Daily Dev Digest

on:
  schedule:
    - cron: "30 2 * * *" # 8:00 AM IST
    - cron: "30 7 * * *" # 1:00 PM IST
    - cron: "30 11 * * *" # 5:00 PM IST
    - cron: "30 15 * * *" # 9:00 PM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Daily Dev Digest Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Digest
        env:
          FEED_SOURCES: ${{ secrets.FEED_SOURCES }}
        run: python generate_digest.py

      - name: Clone Blog Repo
        run: |
          git clone https://x-access-token:${{ secrets.BLOG_REPO_TOKEN }}@github.com/mohansagark/next-gen-portfolio.git blog

      - name: Ensure blog/src/blog/posts folder exists
        run: |
          mkdir -p blog/src/blog/posts/

      - name: Copy MDX files to blog
        run: |
          cp -v digests/*.mdx blog/src/blog/posts/ || echo "⚠️ No .mdx files to copy"

      - name: Commit and Push to Blog Repo
        run: |
          cd blog
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/blog/posts/*.mdx
          git commit -m "🔁 daily dev digest $(date '+%Y-%m-%d %H:%M')" || echo "⚠️ Nothing to commit"
          git push

      - name: Trigger Vercel Rebuild
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
